### ISSUE TITLE
[Bug] MQTT plugin causes router to crash if client repeatedly creates and closes a session

### ISSUE THREAD

**Issue by ahiggins-123** [eclipse-zenoh/zenoh-plugin-mqtt#39] opened 2024-02-07 03:37 UTC
### Describe the bug

Not exactly sure which project to log this issue against, but the issue only seems to occur when I include the MQTT plugin in my router config...

I have reduced the problem down to:
 - a Zenoh router using the default config (https://github.com/eclipse-zenoh/zenoh/blob/master/DEFAULT_CONFIG.json5), adding the MQTT plugin on port 1884: [upstream-plus-mqtt.json](https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/files/14188665/upstream-plus-mqtt.json) (Github doesn't allow attachments with the `json5` extension, so just renamed)

 - a minimal Python client that loops: creating a session, publishing a single message, and closing the session
 
This eventually results (usually within a couple of minutes) in the Zenoh router crashing:
[zenohd-crashes.log](https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/files/14188612/zenohd-crashes.log)
(I couldn't find `-dbg` packages for Ubuntu/debian that would give me symbols for a better stacktrace?)

The code for my test client/app:
```python
#!/bin/env python3

import time
import json
import logging
import argparse
import zenoh


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    args = parser.parse_args()
    logging.basicConfig(level=logging.WARNING - (10 * args.verbose))

    while True:
        try:
            session = zenoh.open()
            pub = session.declare_publisher('foo/bar')
            pub.put(json.dumps('simple message'))
            pub.undeclare()
            session.close()

        # zenoh.ZError is not accessible?
        except Exception:
            logging.exception('Waiting for router connection:')
            time.sleep(5)
```

### To reproduce

1. Run the Zenoh router using the attached config
2. Run the client app
3. Wait for zenohd to crash

### System info

Platform:
Ubuntu 20.04 64bit, Zenoh binaries installed via apt (https://github.com/eclipse-zenoh/zenoh?tab=readme-ov-file#linux-debian)

Zenoh version:
`zenohd v0.10.1-rc-1-g15b36a0f built with rustc 1.72.0 (5680fa18f 2023-08-23)`

**Comment by gmartin82** [comment] 2024-02-07 08:43
At first look the problem is manifesting as a panic in one of the ntex packages which the plugin depends on. Ntex being the MQTT server implementation that the plugin uses so it’s entirely possible this issue only affects the MQTT plugin.

I’m going to look into this further and will let you know what I find.

**Comment by gmartin82** [comment] 2024-02-07 15:30
@ahiggins-123 Unfortunately I haven't been able to reproduce the failure on my Ubuntu system.

Could you please try again with the RUST_LOG environment variable set to trace (RUST_LOG=trace)? Hopefully that should give a bit more information about what is happening within ntex and the router at the time of the failure.

Also are you running any MQTT applications duing your testing when the failure occurs? Or is the only thing running your Python test app (which sends messages via Zenoh to the router)?

**Comment by ahiggins-123** [comment] 2024-02-07 22:23
So far I have not been able to reproduce the issue at all with `RUST_LOG=trace` (still reproducing it when I remove that from the command-line though).

As for other MQTT applications, after double checking I do have mosquitto running in the background, and it was configured to bridge to the MQTT-plugin. After some further testing, it does appear that mosquitto is required to be running to reproduce the issue.

My mosquitto conf drop-in is (the main mosquitto.conf is left untouched):
```
$ cat /etc/mosquitto/conf.d/mosquitto-bridge-zenoh.conf
# Allow anonymous connections from `mosquitto_sub` clients
allow_anonymous true

# Redirect logs to be available via: `journalctl -u mosquitto -f`
log_dest stdout

listener 1883 localhost

connection mosquitto_zenoh_bridge

# zenoh-plugin-mqtt is listening on port 1884
address localhost:1884
topic # both 0

# zenoh-plugin-mqtt does not support... whatever this option does
try_private false

# Remap mosquitto broker status information from default of:
# $SYS/broker/connection/<remote_clientid>/state which is not a valid 
# zenoh key
notification_topic mqtt/broker/connection/mosquitto_zenoh_bridge/state
``` 

Other than mosquitto there is nothing else MQTT-related running on my PC, or any external device that would be connecting in, really hoping this is the last additional thing...

**Comment by gmartin82** [comment] 2024-02-08 17:19
Thanks, I've been able to reproduce the failure with debug builds. I'm still looking into the issue but I've attached the backtrace.

[zenoh-mqtt-failure.log](https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/files/14212518/zenoh-mqtt-failure.log)

**Comment by gmartin82** [comment] 2024-02-14 14:22
After further investigation I've been able to reproduce the failure without repeatedly opening and closing Zenoh sessions with the modified Python program below:

`#!/bin/env python3

import time
import json
import logging
import argparse
import zenoh


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    args = parser.parse_args()
    logging.basicConfig(level=logging.WARNING - (10 * args.verbose))

    try:
        session = zenoh.open()
        pub = session.declare_publisher('foo/bar')

        while True:
            pub.put(json.dumps('simple message'))

    # zenoh.ZError is not accessible?
    except Exception:
        logging.exception('Waiting for router connection:')`

It seems the issue relates to concurrent access to the writer_cache in the NTEX MQTT server memory pool. It isn't intended to be used concurrently and the act of publishing a Zenoh message to an MQTT sink seems to trigger the failure.

While the NTEX MQTT documentation is limited, [this discussion](https://github.com/ntex-rs/ntex-mqtt/discussions/66) may point towards a possible solution to the issue.

**Comment by gmartin82** [comment] 2024-02-19 15:29
I've submitted a PR which addresses the crash. Note that while the PR fixes the crash due to concurrent access it exposes another issue which occurs when data is being forwarded from Zenoh at a high frequency. While data is successfully forwarded to connected MQTT clients ntex-mqtt isn't able to handle new MQTT connection requests or keep-alive messages. This seems to be a limitation of the current ntex-mqtt implementation.

I was only able to trigger this secondary issue when sending data as fast as possible from Zenoh to MQTT. When small sleeps were introduced between publishing messages (e.g. 1 ms) everything worked as expected. As such it is expected that the implementation should be able to handle the frequency of messages for normal use cases.

**Closed** 2024-02-20 11:11 UTC
Labels: bug
